### PR TITLE
Add support for Semaphore's Servers & Deploys API

### PR DESCRIPTION
**Pull request by pipt**

### CODE REVIEW

**Comment by Efesto** [comment]
Any news on this PR? Would be quite useful to me and my team :)

**Comment by Simbul** [comment]
I'm sorry. The truth is that I'm not using the gem myself anymore and I lost track of this PR.
I've merged it in now. If you're considering adding new features to Semaphoreapp, I would recommend starting a fork 😃 

Thanks for the original contribution @pipt!

**Comment by pvdb** [comment]
> ... and I lost track of this PR.

_"lost track"_ ... bit of an understatement, after almost 4 years, no?!? 😜

**Comment by Simbul** [comment]
I don't think the expression implies a specific amount of time, but I get your point 😉

**Pull request merged**
